#!/bin/sh

ID="$(nmcli -f DEVICE con show --active | head -n 2 | tail -n 1)"

json_wrap() {
	echo "{\"type\": \"$1\", \"name\": \"$2\"}"
}

net_stat () {
	if (ping -c 1 archlinux.org || ping -c 1 google.com || ping -c 1 bitbucket.org || ping -c 1 github.com || ping -c 1 sourceforge.net) > /dev/null; then
		case $ID in
			e*)
				json_wrap 'ethernet' "$ID";;
			w*)
				json_wrap 'wifi' "$ID";;
			*)
				json_wrap 'unknown' "$ID";;
		esac
	else
		json_wrap 'disconnected' 'Disconnected'
	fi
}

net_stat
