#!/bin/sh
# [ -z ${EDITOR+x} ] will only return true if it is UNSET, empty strings count as set
[ -z ${EDITOR+x} ] && export EDITOR="nvim"
#source ~/.config/lf/lficons

set -e

if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
	lf "$@"
else
	mkdir -p /tmp/lf
	lf -log "/tmp/lf/$$.log" "$@" 2> >(tee -a "/tmp/lf/$$-stderr.log" >&2)
fi
